# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 ./splyne --count --select=E9,F63,F7,F82 --show-source --statistics
        # if there are not syntax error, apply linter with config
        poetry run flake8 ./splyne --count --config ./config/flake8/config.flake8 --statistics
    - name: Test with pytest
      run: |
        poetry run pytest --doctest-modules ./splyne ./tests
